### PR TITLE
WeightPanel is now working with BlobViz

### PR DESCRIPTION
**Pull request by rahatzamancse**
I have successfully wired the WeightPanel and Blobviz.

But if you change the weights, you may not notice any difference for the radius of the nodes, because the difference is too small. 

Things that need your review to change:
1. The nodes radius range: For now it is minimum 1px and maximum 30px. 
2. The scale of the radius is logarithmic. We can change it to linear/log-log or something else. We can also make it selectable for the user.
3. I have noticed that for some nodes, the calculated weight is 0. I will look into this more and discuss with you about how to handle those cases.

### CODE REVIEW

**Comment by enoriega** [comment]
Thanks @rahatzamancse 

I tested this on the "production" data and I don't see any discernible change on the radius. I see the animation redraws but no change to the huge nodes. Maybe the radius is already saturated by the high aggregated frequency of each node.

In any case, I suggest you should:

- Make the radius scale linear, because if it is logarithmic, it will saturate pretty quickly and the user might not notice a meaningful change
- Map  the range of the weight function to a scaled down radius length function such that the slider changes result on a smooth change of radius. This means that you will need to compute the max weight value on the back end (i.e. run the function as if all the sliders are cracked all the way right), then scale down the weight to a radius a value within [1px, 30px] on the front.

See the animation below.

weights

**Comment by enoriega** [comment]
@rahatzamancse that sounds good. Can you please implement this scaling strategy in your next commit?

**Comment by rahatzamancse** [comment]
I just merged to the updated new main branch and added the maximum node radius slider. This should be merged now.

**Comment by enoriega** [comment]
Thanks! @rahatzamancse

**Pull request merged**
