### PR TITLE
Updated Search Results and Minor bug fixes

### PR DESCRIPTION
**Pull request by rahatzamancse**
@enoriega, I had to change a line in dependencies.py file, hopefully it will not break your searching capability in other components. I had to do that because the search result was sending all lower case node ids, which when later used to query in the graph data, returns a KeyError (because the actual id was uppercase). Please have a look and suggest any changes if needed.

Now the search result of Entity Panel is the same as yours. I just refactored and reuse your component. Other minor bugs of #32 are also fixed here. 

Can you also verify if the third bug of #32 is improved or the same? In my end, it seems to improve.

### CODE REVIEW

**Comment by rahatzamancse** [comment]
I reverted the changes. I was not sure if all the ids have uppercase after first ":". Now everything should be good to go.

**Comment by enoriega** [comment]
@rahatzamancse Thank you!

**Comment by enoriega** [comment]
@rahatzamancse please don't close the PR and/or erase the branch until I have the chance to validate it and merge it into main

**Comment by rahatzamancse** [comment]
@enoriega , this branch is the same as new one. I just deleted/closed this branch because there was a commit with wrong user name. I would suggest merging #36 instead of this one.

**Comment by enoriega** [comment]
@rahatzamancse Got it. Then #36 contains all the fixes that were started in this?

**Comment by rahatzamancse** [comment]
Yes. The changes are basically same, I just sqashed all the commits into one.

**Pull request closed without merging**
